bridges = []
persistence_dir = ''
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'hc-run-agent'
keystore_file = 'testAgent'
name = 'testAgent'
public_address = 'HcScjN8wBwrn3tuyg89aab3a69xsIgdzmX5P9537BqQZ5A7TEZu7qCY4Xzzjhma'
test_agent = true

[[dnas]]
file = '/home/hedayat/holo/hUdemy/dist/hUdemy.dna.json'
hash = 'Qmbqd6FeEVvx8JTDyt8uFX64eJEd7mhxZN6woMtGFnoBxm'
id = 'hc-run-dna'

[[instances]]
agent = 'hc-run-agent'
dna = 'hc-run-dna'
id = 'test-instance'

[instances.storage]
type = 'memory'


* Interfaces is an array of configurations of the channels (e.g. http or websockets) 
* that the Conductor will use to send information to and from instances and users.
* Details: https://developer.holochain.org/docs/guide/conductor_interfaces/

[[interfaces]]                
id = 'websocket-interface'      * Give an ID of your choice to this interface

[[interfaces.instances]]
id = 'test-instance'            * Reference that needs to be made available via that interface

[interfaces.driver]
port = 8888                     * The port on the device to run this interface over
type = 'websocket'              * http or websockets


[logger]
state_dump = true
type = 'debug'

[logger.rules]
rules = []

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
